version: '3.9'

services:
  web:
    container_name: KOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7021:7021"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7021
