name: King of Tokyo

on:
  push:
    branches: [ '**' ]
  #pull_request:
    #branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Check format issues
        run: dotnet format --verify-no-changes -v d
      #- uses: actions/checkout@v2
      #- name: Build the Docker image
      #  run: docker build . --file Dockerfile --tag kot-image:$(date +%s)
      - uses: actions/checkout@v2
      - name: Build docker-compose image
        run: docker-compose build web
