name: King of Tokyo

on:
  push:
    branches: [ 'feature/deploy-kot' ]

jobs:
  build-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: trainer
    steps:
      - uses: actions/checkout@v3
      # Build docker-compose image
      - name: Build docker-compose image
        run: docker-compose build web
      # Log in to Docker Hub
      - name: Login to Docker Hub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag king-of-tokyo-webapi-team2_web:latest ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Remove and logout
      - name: Remove the image and logout from Docker
        run: |
          #docker image prune -a -f
          docker rmi ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
          docker logout

  deploy-dev:
    runs-on: ubuntu-latest
    #needs: build-image
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "USERNAME=${{secrets.DOCKER_USERNAME}}" >>.env
          echo "IMAGE_NAME=kot-image" >> .env
          echo "IMAGE_TAG=3805370181" >> .env
          cat .env
      - name: Get Docker Credentials
        run: |
          echo "${{secrets.DOCKER_USERNAME}}" > docker_user
          echo "${{secrets.DOCKER_PASSWORD}}" > docker_pass
      - name: Get PK
        run: |
          echo "${{secrets.SSH_DEV_SERVER_PK}}" >> pk
          chmod 400 pk
      - name: Copy files for deployment
        run: |
          scp -i pk -o StrictHostKeyChecking=no .env ./deploy-docker-compose.yaml docker_user docker_pass ubuntu@${{secrets.DEV_SERVER_IP}}:/home/ubuntu

      - name: Deploy KOT Web API into Dev Server
        run: |
          ssh -i pk -oStrictHostKeyChecking=no ubuntu@${{secrets.DEV_SERVER_IP}} <<-SHELL
            docker login -u $(cat docker_user) -p $(cat docker_pass)
            docker-compose -f deploy-docker-compose.yaml up -d
            docker logout`
            rm -f docker_user 
            rm -f docker_pass
          SHELL

