name: King of Tokyo

on:
  push:
    branches: [ 'main' ]

jobs:
  build-image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # Build docker-compose image
      - name: Build docker-compose image
        run: docker-compose build web
      # Log in to Docker Hub
      - name: Login to Docker Hub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag king-of-tokyo-webapi-team2_web:latest ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Remove and logout
      - name: Remove the image and logout from Docker
        run: |
          docker image prune -a -f
          docker logout

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo "USERNAME=${{secrets.DOCKER_USERNAME}}" >>.env
          echo "IMAGE_NAME=kot-image" >> .env
          cat .env
      - name: Get Docker Credentials
        run: |
          echo "${{secrets.DOCKER_USERNAME}}" > docker_user
          echo "${{secrets.DOCKER_PASSWORD}}" > docker_pass
      - name: Get PK
        run: |
          echo "${{secrets.SSH_EC2}}" >> pk
          chmod 400 pk
      - name: Copy files for deployment
        run: |
          scp -i pk -o StrictHostKeyChecking=no .env  ./dev-docker-compose.yml docker_user docker_pass ubuntu@${{secrets.IP_EC2}}:/home/ubuntu
      - name: Deploy KOT Web API into Dev Server
        run: |
          ssh -i pk -oStrictHostKeyChecking=no ubuntu@${{secrets.IP_EC2}} <<-SHELL
            sudo docker login -u $(cat docker_user) -p $(cat docker_pass)
            sudo docker-compose -f dev-docker-compose.yml  up -d
            sudo docker logout
            rm -f docker_user 
            rm -f docker_pass
          SHELL

