name: King of Tokyo

on:
  push:
    branches: [ 'feature/deploy-kot' ]

jobs:
  build-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # Build docker-compose image
      - name: Build docker-compose image
        run: docker-compose build web
      # Log in to Docker Hub
      - name: Login to Docker Hub
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      # Tag the Docker image
      - name: Tag the Docker image
        run: docker tag king-of-tokyo-webapi-team2_web:latest ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Push the Docker image to Docker Hub
      - name: Push the Docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/kot-image:$GITHUB_RUN_ID
      # Remove and logout
      - name: Remove the image and logout from Docker
        run: |
          docker image prune -a -f
          docker logout

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get PK
        run: |
          echo "${{secrets.SSH_DEV_SERVER_PK}}" >> pk
          chmod 400 pk
      - name: SSH Dev Server
        run: |
          ssh-keygen -R {{secrets.DEV_SERVER_IP}}
          ssh -i pk ubuntu@${{secrets.DEV_SERVER_IP}} docker --version

